#!/usr/bin/env bash

sudo echo "Setting environment to PROD."
cp ./.env ./~.env.temp
sed "s|\(export APP_SETTINGS=\).*|\1\"production\"|g" ./.env >> ./.temp
sed "s|\(export FLASK_ENV=\).*|\1\"production\"|g" ./.temp >> ./.temp2
mv ./.temp2 ./.env
rm ./.temp

echo "Building Docker image..."
if ! sudo docker build -t hypechat-server:latest .; then
    echo "Failing to build Docker image."
    mv ./~.env.temp ./.env
    exit 1
fi

echo "Pushing Docker image to Heroku..."
if ! sudo heroku container:push web --app hypechat-server; then
    echo "Failing to push Docker image to Heroku."
    mv ./~.env.temp ./.env
    exit 1
fi

echo "Releasing Heroku image..."
if ! sudo heroku container:release web --app hypechat-server; then
    echo "Failing to release Heroku image."
    mv ./~.env.temp ./.env
    exit 1
fi

echo "Resetting environment as last state"
mv ./~.env.temp ./.env